### ISSUE TITLE
Clarify Early Stopping Loss

### ISSUE THREAD

**Issue by BrianMiner** [ElicitHub/odsc-west#1]
Hello - 
I attended your presentation at ODSC. It was really interesting! I am wondering if you can explain a bit more about the loss calculation?

For example, the loss associated with **picking the new coupon** at day 1 is (in words): "What is the cost we incur if we made a bad choice and the old coupon was better?".  We need to have an estimate of how many less responders we would see over some period of time multiplied by their margin.  You are picking 180 day as you expect that you'd have the chosen coupon in place after making a choice and that you see 1000 visitors a day on your website and with the old coupon. each missed out on buyer would generate on average $100. **Is all of this correct?**

I think we want to use the probability that old is actually better to weight the above loss (as some draws show old better than new, while others show new better than old).

Then I get lost...... Why set some to zero where old is worse than new? Why divide by 4000 (total number of posteriors)? Why use 500 for the days when looking at the cost of waiting 1 more day)?

**Comment by BrianMiner** [comment]
@elicit-bergmann  is this repo being monitored?

**Comment by elicit-bergmann** [comment]
Thank you. 

When old is worse than new, then old isn't better. So we don't include that as part of the loss. We divide by 4000 because there are 4000 draws and each draw is a possible conversion rate. Each draw has uniform probability so we get expected value by multiplying visitors * conversion rate * (1/4000) * margin and then summing the result. 

We use 500 for waiting 1 more day because we are only wrong about either the test or control group and there are, on average, 500 of these per day. 

Hope this helps.

**Comment by BrianMiner** [comment]
Thanks for the reply - I did not get notification for some reason.

I think I follow the divide by 4000 bit....but not entirely.

Also -It seems like waiting 1 more day only experiences the loss (opportunity cost) of not picking the correct one for 1 day no?

This part seems the most difficult to me. Was all this explained in the Gelman book you referenced or did you arrive at it personally?

**Comment by elicit-bergmann** [comment]
You can simulate 4000 draws from a normal distribution:
```
x <- rnorm(4000, 0.5, 0.1)
```
The expected value of x is 0.5 which you can find by:
```
sum(x) /4000
```
Which is really the same as
```
sum( x * 1/4000)
```
Each draw has equal probability. There are 4000 draws so each draw has 1/4000 probability. In the example, we are looking for the expected loss so we multiply the sum by 1/4000 to get the expected value.

And yes, you can argue that you should only consider 1 more day for the loss of waiting one more day rather than accumulating the losses for the whole test to-date. This would be the same as ignoring sunk cost. If you only consider the next day your tests will take longer and you will make fewer wrong decisions. 

But, I also think it is reasonable to consider the whole cost of the test when making this decision -- resulting in lower test costs but more wrong decisions. There are fixed costs each day you run the test and each day you wait could delay the next incremental improvement. These are not factored into our example here but we could add this to the 'wait 1 more day' loss function as you suggest. 

No, this specific loss example is not in Gelman's book but the decision approach is from his book and I have derived the loss function from other sources which I can't seem to find today but which I was able to support via simulation as indicated on the last couple of slides. I didn't have time in the class to show a comparison using bayesfactors or sequential testing using p-values but it compares favorably and has the benefit of not requiring one to make a decision about which sequential p-value method to choose or which bayesfactor limits to choose and, of course, can be extended to include other criteria in the loss function.

**Comment by BrianMiner** [comment]
Regarding the 4000, I see - you are taking into account the proportion where old isnt better (but zeroing the loss).  Is that right?

**Comment by elicit-bergmann** [comment]
Correct

**Comment by elicit-bergmann** [comment]
Thanks for the conversation
